### ISSUE TITLE
Add support for ingest from Google Sheets

### ISSUE THREAD

**Issue by dosumis** [obophenotype/CCF_tools#13]
Ingest currently works by copying and pasting content into this repo.  It would be much better if we could support ingestion directly from google sheets.  There are two options for this:

1. Ingest from published TSVs and add TSV URLs to var used by MakeFile
2. Ingest directly from sheets - including working with access requirements. 

@emquardokus - please comment on which approach we should prioritise.

**Comment by emquardokus** [comment]
@dosumis The ASCT+B reporter already has code that allows  Google sheets with permissions set to "Anyone with link can view" urls to call ASCT+B google sheets, Also we've added support for .csv 
Is it possible to utilize same/similar method?

**Comment by bherr2** [comment]
If you want a low-entry way of doing it, Google Sheets can export to CSV via URL using a template like this:

```python
f"https://docs.google.com/spreadsheets/d/{sheetID}/export?format=csv&gid={sheetGID}"
```
 
It's then easy enough to convert to .tsv (why do people still use TSV? I used to do that a long time ago but switched to csv a long time ago to avoid formatting issues).

Another way, which requires more post-processing depending on what you're doing is to use the ASCT+B API:

```python
f"https://asctb-api.herokuapp.com/v2/csv?output={format}&csvUrl={csvURL}"
```

format can be jsonld, graph, or json. Depending on your needs, all three are useful.
