### ISSUE TITLE
Switch build to use ASCT-b tables

### ISSUE THREAD

**Issue by dosumis** [obophenotype/CCF_tools#2]
The current build uses out of date representations of ASCT-b tables stored in the resources folder on this repo.

This needs to be switched to consume ASCT-b tables with Uberon/CL mapping:

https://docs.google.com/spreadsheets/d/1j_SLhFipRWUcRZrCDfNH15OWoiLf7cJks7NVppe3htI/edit#gid=1283919854

The runner script currently uses ccf_tools.parse_CCF_tsv.
![image](https://user-images.githubusercontent.com/112839/96256651-f5f3fa00-0fb0-11eb-8067-0b5490bfa64c.png)

This needs to be switched out for a new ccf_tools function that parses flattened, mapped ASCT-b tables.

The runner & Makefile will then need to be updated.

**Comment by dosumis** [comment]
HI @emquardokus  - are you planning to work on this.  Happy to do a screenshare to work together on it if you like &  to review any pull requests.  If we can run this soon on flattened tables, we can work on turning the reporting output into Uberon tickets & items for community discussion.

**Comment by emquardokus** [comment]
Hi @dosumis -- yes it would be good to walk one of these through to the end.  I've been working to get all organ sheets into a standardized format so one code would work on all.  Sheets from original authors had features making them difficult to use directly. Being able to turn it into a pipeline would be great.

**Comment by dosumis** [comment]
Think we don't need to wait for all sheets to be in final spec before working on this.  Having a few sheets in a near final state would be fine as long as radical changes not expected.

Have you considered using some kind of formal spec for defining flattened tables.  Could be as simple as a list of valid header names.  If you wanted to attach some doc to this, you could use YAML.   Or if you want something slightly more sophisticated, you could use JSON schema (converting TSV  to a dictionary of lists to test).   This would allow for specifying columns as compulsory and also autogenerating html doc.

**Comment by dosumis** [comment]
It would be better not to flood the Uberon tracker with all issues from all tables - better to gradually add them as tables become ready to process.

**Comment by emquardokus** [comment]
Agreed!  We needed the standardized format for 2 other items so it took some time for agreement.  I should have at least 4 tables in that format by end of this week. Spleen, Heart, Kidney and Large Intestine and I'm currently reviewing the vasculature table that Griffin just pulled together over our Thanksgiving holiday last week. When might be a good time to meet for working through this?

**Comment by emquardokus** [comment]
Talked to Amy Bernard and Jeremy Miller from Allen Institute last week; the Brain ASCT-B table that they contributed to our effort has not been formally put into ontology format.  What we have has been corrected from errors and issues found on the website and 3D brain models we had provided, so according to Amy the Human brain table is the most up to date that exists and not published anywhere, so want to share with you since I know you are officially funded now with Allen Institute. The primary motor cortex has cell types, but the rest is just brain hierarchy.

**Comment by dosumis** [comment]
- [x] Write or link to spec ASCT-b tables https://docs.google.com/spreadsheets/d/1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0/edit?ts=6005953f#gid=2034682742
 - [ ] Design architecture or parser:
   - Input = TSV rows 11 + 
    - [ ] parser for headers   AS/1 | AS/1/LABEL | AS/1/ID. .... indefinite number entries
