### ISSUE TITLE
Test CL -> AS relationships.

### ISSUE THREAD

**Issue by dosumis** [obophenotype/CCF_tools#51]
CL->AS  CL_x -> AS_y where x and y are the largest numbers CL and AS respectively for that row. 

Test 1: SPARQL ASK
CL part_of or overlaps AS
If this passes then CCF.owl gets  CL_x part_of some AS_y.
Fails go in a separate log file: Kidney_AS_CT_strict.log

Test 2: (if test 1 doesn't pass) SPARQL ASK
Find all subclasses of CL term (reflexive)
Test each for whether it is part_of/overlaps AS
Test whether AS has_part some CL.
TEST 2 fails go in the main log file.
If this passes, CCF.owl gets AS_y has_part some CL_y AND add to the AS_has_part_CT_log.tsv

**Comment by anitacaron** [comment]
Is the indirect relationship also needs to be checked?
