### ISSUE TITLE
Add ASCT+B csv integrity checks.

### ISSUE THREAD

**Issue by dosumis** [obophenotype/CCF_tools#90]
Current spec (1.2) is here: https://docs.google.com/document/d/13xBfR6aM-BRpTtw64DYiVYlvRT9GWcrtJYK1oRhRgUc/edit# (Note- we need to be informed of changes & new version releases!)

Minimal checks (sufficient for this ticket):
1. Check correct number metadata rows (in 1.2 this is 10 rows)
2. Check correct column headers & column header order
   * AS/1    AS/1/LABEL    AS/1/ID ,  AS/2    AS/2/LABEL    AS/2/ID etc
   * CT after AS
   * CT/1   CT/1/LABEL    CT/1/ID ,  CT/2    CT/2/LABEL    CT/2/ID etc

If these fail - stop all other attempts at processing.  Add exception message to existing error log file for table.

**Comment by emquardokus** [comment]
We allow any column order or number of columns per entity as needed which can also include AS/1/NOTES, AS/1/ABBR (for common abbreviation used).  These are not always added, only as needed.  
We got away from strict numbers or positions of rows and columns because exceptions kept cropping up and then it would shut down everything using table, so we go based on column header format Where the 2nd position number plus content identifier determines group of attributes "AS/n/content identifier", "CT/n/content identifier", or "BX/n/content identifier"  where BX indicates Biomarker X type could be protein, proteoform, gene, lipid, metabolite;  n is a positive, non-zero integer; content identifier can be nothing for root entity, LABEL for ontology rdfs:label, ID for ontology short ID (example: uberon: format), NOTES for any text info an author needs to communicate with us about the entity--this is often that it's not in ontology or they filled out NTR issue, ABBR is common abbreviation used for entity, other possibilities may arise as needed but would always be in 3rd position in  XX / YY /ZZ format .

**Comment by emquardokus** [comment]
Likewise, row placement should NOT be counted on as having to remain static.  Tables are worked on by authors and insertion or deletion of rows or columns (as labeled above) are not prohibited and often occur.

**Comment by dosumis** [comment]
Proc code: https://github.com/obophenotype/CCF_tools/blob/master/src/ccf_tools.py#L74

Current architecture:

1. Takes all columns matching regex (AS|CT)/.+ - in order.
2. Split these into groups of 3. # This is what currently causes problems.
3. For each group of 3, - further matches are based on splitting header string on '/' and matching components.

@emquardokus - I assume ordering is relevant in that AS/n columns will always be immediately to the left of AS/n+1 coulumns.  Please confirm.

**Comment by bherr2** [comment]
You should consider using the CCF-API that already does this logic.

**Comment by dosumis** [comment]
> You should consider using the CCF-API that already does this logic.

Can we access the live/changing tables in this way or just the release versions?

**Comment by bherr2** [comment]
Yep! I described how to do that for exporting to OWL here: https://github.com/obophenotype/CCF_tools/issues/98#issuecomment-964427561

You can also change the format from owl (though you might like this one the best) to json (the most straightforward translation of tables to rows), graph (nodes and edges in json format), or json-ld.

It will query google sheets or any other CSV url on the fly for you, translate in a set way, and return the results.

**Comment by bherr2** [comment]
If there are any issues you find or things you'd like us to improve, let us know and I can have folks work on it.

**Comment by anitacaron** [comment]
@dosumis, to give you an idea of how is the JSON output extracted only AS and CT objects of the first two rows from the Kidney table:

```
{
  "anatomical_structures": [
  {
    "name": "kidney",
    "id": "UBERON:0002113",
    "rdfs_label": "kidney"
  },
  {
    "name": "kidney capsule",
    "id": "UBERON:0002015",
    "rdfs_label": "kidney capsule"
  }
  ],
  "cell_types": [
    {
      "name": "capsule mesenchymal stromal cell",
      "id": "",
      "rdfs_label": ""
    }
  ]
},
{
  "anatomical_structures": [
  {
    "name": "kidney",
    "id": "UBERON:0002113",
    "rdfs_label": "kidney"
  },
  {
    "name": "cortex of kidney",
    "id": "UBERON:0001225",
    "rdfs_label": "cortex of kidney"
  },
  {
    "name": "outer cortex of kidney",
    "id": "UBERON:0002189",
    "rdfs_label": "outer cortex of kidney"
  }
  ],
  "cell_types": []
}
```

Then I can convert it to CSV, then will be good for the rest of the parse function after some modifications.

**Comment by anitacaron** [comment]
@bherr2, for the Ureter table, the JSON output is missing some AS values. Do you have an idea what's happening?

Here is an extract for the first row:

```
"anatomical_structures": [
      {
        "name": "ureter",
        "id": "UBERON:0000056",
        "rdfs_label": "ureter"
      },
      {
        "name": "urothelium of ureter",
        "id": "",
        "rdfs_label": ""
      }
    ],
    "cell_types": [
      {
        "name": "urothelium",
        "id": "CL:1001428",
        "rdfs_label": "ureter urothelial cell"
      },
      {
        "name": "basal cell of ureter urothelium",
        "id": "",
        "rdfs_label": ""
      }
    ],
```

**Comment by bherr2** [comment]
This ureter? https://docs.google.com/spreadsheets/d/1tK916JyG5ZSXW_cXfsyZnzXfjyoN-8B2GXLbYD6_vF0/edit#gid=1106564583

It is missing names in column D (AS/2) -- if no name, it doesn't exist. Simple solution is to just copy the AS/2/LABEL to AS/2 in the sheet @emquardokus can confirm / fix.

**Comment by emquardokus** [comment]
@anitacaron @bherr2 I duplicated AS/2/LABEL into AS/2 fields to resolve. This is fixed now.
