### ISSUE TITLE
Ensure subClassOf relationships are not being missed.

### ISSUE THREAD

**Issue by dosumis** [obophenotype/CCF_tools#94]
According to the spec the redundant graph should have the subClassOf closure, but recent testing has shown that not to be the case at present.  These axioms are in the closure graph, so pointing the subClassOf check at that graph will fix. (I suspect that the main checks will all work fine with no graph specification at all - I can't think of a theoretical reason why this would not be the case).

**Comment by dosumis** [comment]
I just checked the code - looks like you're already using the closure graph for subClassOf

https://github.com/obophenotype/CCF_tools/blob/master/src/uberongraph_tools.py#L40

**Comment by dosumis** [comment]
And you're using the full ontology for the indirect check, which is also correct:

https://github.com/obophenotype/CCF_tools/blob/master/src/uberongraph_tools.py#L137

**Comment by dosumis** [comment]
Closing as not needed.

**Comment by anitacaron** [comment]
I think the problem was with the CCF graphs repository. The query was only using the non-redundant graph. 

https://github.com/obophenotype/CCF_graphs/pull/3

**Comment by balhoff** [comment]
@dosumis @anitacaron FYI I think all issues are fixed with getting subclass relations into the right graphs, so please let me know if anything seems off now.
